### ISSUE TITLE
Build Spam Detector

### ISSUE THREAD

**Issue by smit8585** [GDSC-AUM/OpenOcto-AI-ML#5]
**Description**
Classify spam and not spam messages.

**Additional**
Add your file in [NLP/Spam_Detection](https://github.com/GDSC-AUM/OpenOcto-AI-ML/tree/main/NLP/Spam_Detection) directory.
Also update the `DOC.md` with your model description.

**Comment by DevChoganwala** [comment]
Hey @smit8585, I would like to work on this issue!

**Comment by smit8585** [comment]
Yes @saiharsha-22 , you can work on this issue.

**Comment by saiharsha-22** [comment]
Thank you @smit8585 . I will raise pull request please review it once.
